### ISSUE TITLE
Cannot open include file ldd_colors_declarations.bin

### ISSUE THREAD

**Issue by MrGibbage** [pugwonk/lego-animate#12]
I did check the "running the application FAQ" here:
http://ldd2povray.lddtools.com/index.php?p=3_2_Running-the-application

My povray.ini file has the line Library_Path=\\.\LDDIncludes
I have the LDD to Povray converter open when running POV-ray
I've tried the 32 bit and the 64 bit pov ray
I did reboot after installing LDD to POV-Ray

I always get the error 
Parse error: Cannot open include file ldd_colors_declarations.bin

Here's my .ini file (C:\Users\Skip\Documents\LEGO Creations\pov\LinearActuator.ini):

Input_File_Name="C:\Users\Skip\Documents\LEGO Creations\pov\LinearActuator.pov"
Library_Path="\\.\LDDIncludes"
Display=On
Verbose=On
Width=2560
Height=1440
Output_Alpha=On
Antialias=On
Sampling_Method=1
Antialias_Threshold=0.3
Antialias_Depth=3
Jitter=On
Jitter_Amount=1.0
Quality=11

Here's my LCC to POV Ray path settings:
db .lif file location C:\Users\Skip\AppData\Roaming\LEGO Company\LEGO Digital Designer\
Output path for includes c:\temp
POV-Ray include path: \\.\LDDIncludes

my c:\temp is full of .bin files (and nothing else. I just added it tonight. It's not full of other typical "temp" garbage)

My model is a technic model. Here's the .pov:
https://pastebin.com/9ugMj4jZ

**Comment by MrGibbage** [comment]
I probably should have mentioned that I am using the x64 version of the converter, version 1.2.12.41399.

**Comment by pugwonk** [comment]
This is an LDD-to-PovRay problem but I'm fairly sure this means you haven't rebooted since installing it and so the virtual directory thing they use to get to the include files isn't running.

**Comment by MrGibbage** [comment]
I think you are right. I re-installed LDD to POV Ray and made sure I did it with administrator rights, and rebooted immediately and it worked. Good call!
